#!/usr/bin/env ruby

require 'date'

POSTS_DIR = '_posts/'
post = ARGV[0]
File.open(POSTS_DIR + Date.today.strftime("%Y-%m-%d-") + post + '.md', 'w') {|f| f.write(
  "---\nlayout: post\nsection-type: post\ntitle: \"Title\"\ncategory: Spring\ntags: [ 'spring', 'java' ]\ncomments: true\n---\n제 블로그의 모든 글은 IMHO로 쓴 것입니다.\n서로에 대한 존중을 담은 덧글을 남겨 소통을 하신다면 더 좋은 글로 발전이 될 수 있을 것 같습니다.\n존중이 담기지 않은 덧글은 언제든 삭제될 수 있습니다.\n감사합니다:)\n")
}
puts('[+] Created ' + post + ' post')
